# Generated by Django 4.2.3 on 2023-07-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='invitecode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
