# Generated by Django 4.2.3 on 2023-07-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_customermodel_alter_card_cvc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='id1',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
