# Generated by Django 4.2.3 on 2023-07-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_plan_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='id1',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customerid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(),
        ),
    ]
