# Generated by Django 4.2.3 on 2023-07-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_card_cardholder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cvc',
        ),
    ]
