# Generated by Django 4.2.3 on 2023-07-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_delete_card_customermodel_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
